// <auto-generated />
using CarService.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CarService.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("CarService.Models.Car", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Color")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Company")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Model")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("Cars");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Color = "Oq",
                            Company = "Chevrolet",
                            Model = "Cobalt",
                            Price = 10000.0
                        },
                        new
                        {
                            Id = 2,
                            Color = "Qora",
                            Company = "Chevrolet",
                            Model = "Malibu",
                            Price = 30000.0
                        },
                        new
                        {
                            Id = 3,
                            Color = "Qizil",
                            Company = "Chevrolet",
                            Model = "Matiz",
                            Price = 5000.0
                        },
                        new
                        {
                            Id = 4,
                            Color = "Ko`k",
                            Company = "Chevrolet",
                            Model = "Neksiya",
                            Price = 7000.0
                        },
                        new
                        {
                            Id = 5,
                            Color = "Oq",
                            Company = "Chevrolet",
                            Model = "Damas",
                            Price = 10000.0
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
